default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  username: postgres
  password: 2000
  host: localhost

development:
  <<: *default
  database: final_capstone

test:
  <<: *default
  database: final_capstone_test

production:
  <<: *default
  database: final_capstone_production
